### ISSUE TITLE
Remove grappelli

### ISSUE THREAD

**Issue by specialunderwear** [sehmaschine/django-filebrowser#14]
Could you please make the grappelli integration optional?

**Comment by leogout** [comment]
I know it is a very old issue, but I found it when searching for a solution to upload files in a TinyMCE editor with django. I did not wanted to use grapelli as well as the others but all the forks of this project which remove it are dead by now.

Here is an alternative for anyone stumbling upon this issue looking for the same thing as me:  https://django-ckeditor.readthedocs.io/
It replaces TinyMCE entirely and adds a file browsing tool which woks nicely out of the box.

By the way, even though I will not use it, thank you for open-sourcing your project @sehmaschine. People often overlook the fact that this is all free and that maybe you are not here to answer their needs.
