### ISSUE TITLE
FileBrowser.show link on admin interface not working on Opera

### ISSUE THREAD

**Issue by daneoshiga** [sehmaschine/django-filebrowser#179]
Version: FileBrowser 3.5.2, Grappelli 2.4.5, Django 1.5.1, Opera 12.16

I have a field, defined this way on the model:

    thumbnail = FileBrowseField(_("thumbnail"), max_length=200,
                            extensions=[".jpg", ".png", ".gif",],
                            format='image', blank=True, null=True)

the admin interface works fine on Chrome and Firefox, but on Opera, clicking on the magnifier icon besides the input doesn't open the popup, and doesn't generate any javascript error on the console either.

The problems appears to be on the way the javascript to opening the popup is added to the link, using the "javascript:" way on the href.

<a href="javascript:FileBrowser.show('id_excerpt_image', '/admin/filebrowser/browse/?pop=1&type=image');" class="fb_show"></a>

**Comment by sehmaschine** [comment]
closing this for now since it's a pretty old ticket. if this issue still exists, please reopen with additional details.
