### ISSUE TITLE
Absolute path returned when retrieving url from FileObject

### ISSUE THREAD

**Issue by dlferro** [sehmaschine/django-filebrowser#186]
Following the example for generating a thumbnail to the changelist, I receive an absolute path to the image file rather than a relative path. Tests ran fine. I can browse images fine. I'm using:

Django: 1.5.1
Pillow: 2.1.0
Filebrowser: 3.5.2

```
    def image_thumbnail(self):
        if self.image:
            image_upload_fileobject = FileObject(self.image.path)
            if image_upload_fileobject.filetype == "Image":
                url = image_upload_fileobject.version_generate(ADMIN_THUMBNAIL).url
                return '<img src="%s" />' % url
        else:
            return ""

    image_thumbnail.allow_tags = True
    image_thumbnail.short_description = "Thumbnail"
```

**Comment by HemantNegi** [comment]
Still getting the same problem. is there a good solution till date

**Comment by v-hunt** [comment]
Got the same issue... 
url returns absolute path instead of relative url to MEDIA settings. Need to use dirty hack for than

**Comment by sehmaschine** [comment]
still not able to reproduce this. if someone who sees this issue could take a look at the test cases and give me some hints I'm happy to take a look.
