### ISSUE TITLE
Problems with django-storages and AWS S3

### ISSUE THREAD

**Issue by oneschilling** [sehmaschine/django-filebrowser#199]
Is django-filebrowser working with django-storages and AWS S3? I set everything up as normal but got an error when using S3BotoStorage with django-storages. It seems like django-filebrowser is using isdir function which S3BotoStorage doesn't provide:
'S3BotoStorage' object has no attribute 'isdir'

I found this which is backing up my guess:
https://github.com/sehmaschine/django-filebrowser/issues/40

**Comment by bsebi** [comment]
`from storages.backends.s3boto import S3BotoStorage
from filebrowser_safe.storage import S3BotoStorageMixin


class S3Storage(S3BotoStorageMixin, S3BotoStorage):
    pass`

**Comment by jdnrg** [comment]
Thanks @SebasSBM 
this is what I did.

`pip install filebrowser_safe` 

and then  
``
from storages.backends.s3boto import S3BotoStorage
from filebrowser_safe.storage import S3BotoStorageMixin
class S3Storage(S3BotoStorageMixin, S3BotoStorage):
   pass
```
