### ISSUE TITLE
Safari 8.0 don't show "Choice" button 

### ISSUE THREAD

**Issue by suhanovv** [sehmaschine/django-filebrowser#246]
django-filebrowser==3.5.7

![2014-10-20 14-29-22 django](https://cloud.githubusercontent.com/assets/3032319/4699689/570fe0f4-5844-11e4-9f07-ed1dd4090954.png)

In previous Safari version(7.1) it's work!

**Comment by sehmaschine** [comment]
Works for me (I see the choice button).

**Comment by sehmaschine** [comment]
Closing this since I'm not able to reproduce it. Please reopen with additional details, if you think this bug still exists.
