### ISSUE TITLE
Invalid syntax with Python 3?

### ISSUE THREAD

**Issue by thinkingcomputing** [sehmaschine/django-filebrowser#247]
This may be obvious to someone more knowledgeable about Python than me but after installing FileBrowser and running my development server (Django 1.7, Grappelli 2.6.2 and Python 3.2.3) it kept telling me there was an invalid syntax error.

I double checked Grappelli and FileBrowser were Python 3 compatible and they are but after doing some investigating it turns out Django doesn't like the use of u'%s' in the code.

For every error it gave I've gone through and changed the code manually to get rid of the 'u' but I was wondering if I should have done something else or if there should be a note in the documentation?

Incidentally, now it is working I really like it and do appreciate the time and effort that has gone in to developing it.

**Comment by timgraham** [comment]
Python 3.2 doesn't support the u prefixes. It was added back in Python 3.3. Django omits the u prefixes and uses `from __future__ import unicode_literals` for Python 3.2 support. Probably not worth adding 3.2 support at this point though.

**Comment by sehmaschine** [comment]
closing this since the tests with python 3.4 and 3.5 are fine.
