### ISSUE TITLE
Question marks in filename

### ISSUE THREAD

**Issue by tomlinl** [sehmaschine/django-filebrowser#260]
If a user uploads a file with a question mark in the name the filename seems to be truncated (dropping the extension). The file still uploads successfully but appears as a directory and not a file in the browser. The directory can't be deleted.

This issue was brought to my attention when I was informed by a user that all images in a particular directory had disappeared. I am not sure how (or if) this is related to the above problem but when I asked for an account of the steps the user had taken at the time, they informed me that they had been attempting to upload an image with a question mark in the filename. I can't seem to get that to happen but it's clear that uploading a file with a question mark causes problems.

I should also mention that the site uses Django (1.6.5), Mezzanine (3.1.9), and Filebrowser (0.3.5)

**Comment by sehmaschine** [comment]
Not able to reproduce this ... uploading with question mark works fine with my setup. Please try to debug this issue and open the ticket with additional details (if you think the bug still exists).
