### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by michalwerner** [sehmaschine/django-filebrowser#267]
I've added .svg to accepted extensions, so files could be uploaded, but it fails to display them on the list.
```
OSError at /admin/filebrowser/browse/

cannot identify image file <File: ................................>
```
Is it possible to use .svg with django filebrowser?

**Comment by sehmaschine** [comment]
More a django then a filebrowser issue I guess, see:
https://code.djangoproject.com/ticket/14092
