### ISSUE TITLE
Converting filenames: Allow to choose between lowering and stripping whitespaces

### ISSUE THREAD

**Issue by cosmokai** [sehmaschine/django-filebrowser#268]
Hi (and thanks for the project)!
We extended the way filenames are converted during upload.
Enabling the setting CONVERT_FILENAME will both lower() the filename and remove spaces from it, but we only needed one (removing the whitespaces). We forked the repository and introduced three new settings:

CONVERT_FILENAME_LOWER
CONVERT_FILENAME_STRIP
CONVERT_FILENAME_STRIP_REPLACEMENT

That way, you can choose which operation should be done.
If you want both, enable CONVERT_FILENAME.
If you only want one, disable CONVERT_FILENAME and enable the one you want.

We have not added full localization and did not add tests, because I simply don't know how to run the test suite. How do you develop the app without django, btw?
If this sounds interesting, I can add localization and tests and open a pull request.

**Comment by sehmaschine** [comment]
How do you develop the app without django, btw?
We don't. Why do you assume that we develop without Django?

If this sounds interesting, I can add localization and tests and open a pull request.
I'm not sure that I like the implementation. There are too many settings IMO. Why not use a function for CONVERT_FILENAME (so everybody can override the function)?

**Comment by sehmaschine** [comment]
closing this since no further comments are given.
