### ISSUE TITLE
incompatible with storages lacking a path implementation

### ISSUE THREAD

**Issue by smcoll** [sehmaschine/django-filebrowser#270]
According to a [docstring in the Django docs](https://github.com/django/django/blob/1.8/django/core/files/storage.py#L109), a `path` property isn't always available on a storage class, as some storage systems can't implement it.  That appears to have been the case since at least 1.0.

[`FileObject`](https://github.com/sehmaschine/django-filebrowser/blob/3.5.7/filebrowser/base.py#L209) seems to rely heavily on a path attribute, though.  This means that some valid storage implementations 
are going to be incompatible with filebrowser.

One place where this is an issue is [this usage of the `version_object` template tag](https://github.com/sehmaschine/django-filebrowser/blob/3.5.7/filebrowser/templates/filebrowser/include/filelisting.html#L9), which is passing a `FileObject` to the [VersionObjectNode](https://github.com/sehmaschine/django-filebrowser/blob/3.5.7/filebrowser/templatetags/fb_versions.py#L21), which in turn leverages the path attribute during type-checking.

Perhaps a solution is to implement `FileObject` in such a way that it can be instantiated from either a path or a File object, or be sure to pass File objects to `VersionNode` in the templates.  Any thoughts?

**Comment by sehmaschine** [comment]
Any example of a storage class without a path property?

**Comment by smcoll** [comment]
AWS S3 backends, for example, since each resource is represented by a full path+filename and there are no real directories.  Here's one in django-storages: https://bitbucket.org/david/django-storages/src/f153a70ba254dc129d9403546809a02256ef75b5/storages/backends/s3boto.py?at=default

**Comment by sehmaschine** [comment]
see #103 ... we currently do not support S3. if someone supplies a patch, I'm happy to take a look (although I'm not able to do any tests with S3).

**Comment by smcoll** [comment]
@sehmaschine on a cursory review of the [14 storage backends in django-storages](https://github.com/jschneier/django-storages/tree/master/storages/backends), only one (mogile) has an implementation of the path attribute.  So this isn't an issue limited to S3 support.  At the very least, perhaps the documentation for django-filebrowser should mention that any storage backend without a path implementation will not be supported.

**Comment by sehmaschine** [comment]
@smcoll Good point, thanks for checking that. If someone adds a patch we'll support these storage engines. I think this has been tried before without any luck though.
