### ISSUE TITLE
Trouble uploading pictures

### ISSUE THREAD

**Issue by dchoruzy** [sehmaschine/django-filebrowser#275]
Hi,
I get this error when trying to upload attached  image:
![lipa2](https://cloud.githubusercontent.com/assets/3209929/8822613/fc9f4e4c-3066-11e5-8b1e-4cee6c1b3b51.jpg)

IOError at /admin/filebrowser/browse/

cannot write mode P as JPEG

any ideas how to fix it? I can upload other images without any problems.

**Comment by sehmaschine** [comment]
There is already a pull-request for this issue.

**Comment by sehmaschine** [comment]
fixed with master
