### ISSUE TITLE
Django 1.8 Warning - url from future tag Removed in Django 1.9

### ISSUE THREAD

**Issue by oelium** [sehmaschine/django-filebrowser#277]
RemovedInDjango19Warning: Loading the url tag from the future library is deprecated and will be removed in Django 1.9. Use the default url tag instead.
RemovedInDjango19Warning

In some template filebrowser use the 'url' tag from the future.py module like this
{% load url from future %}
But in django 1.9 this tag will be removed.
You can find them in
* filebrowser/templates/filebrowser/delete_conform.html line 5
* filebrowser/templates/filebrowser/details.html line 5
* filebrowser/templates/filebrowser/index.html line 5
* filebrowser/templates/filebrowser/include/breacrumbs.html line 2
* filebrowser/templates/filebrowser/include/filelisting.html line 2

so need to use directly {% url 'my_views' %}

![capture du 2015-07-23 14 04 56](https://cloud.githubusercontent.com/assets/13416461/8849921/e4383f66-3143-11e5-8348-7dc38a278845.png)

Best regards

**Comment by sehmaschine** [comment]
fixed with stable/3.6.x (released soon). note that I've used the wrong issue number for the commit ... see #227
