### ISSUE TITLE
version scaling with fixed height and auto width

### ISSUE THREAD

**Issue by toebivankenoebi** [sehmaschine/django-filebrowser#278]
There is a bug in the `scale_and_crop` function in `utils.py` when trying to generate versions with fixed height and automatic width (the other way around it works like a charm). The versions image will be created but with the original size.

Example VERSION definition:
```
FILEBROWSER_VERSIONS = { 
  'medium': {'verbose_name': 'Medium (4col )', 'width': '', 'height': 250, 'opts': ''},
}
```

The reason for it is that the `width` variable is an empty string which gets compared to a float, therefore the if statement returns False and the image won't get resized.

One way to fix it would be to convert the width string into a float for comparing in `utils.py`:
```
66c65
<     if 'upscale' not in opts and x < width:
---
>     if 'upscale' not in opts and x < float(width or 0):
```

Thanks so much for this amazing app!

**Comment by sehmaschine** [comment]
should be solved ... I added some tests as well, so we are able to better fix issues like this in future versions.
