### ISSUE TITLE
DEFAULT_SORTING_BY 'date' incompatible with S3 Storage (Python 3)

### ISSUE THREAD

**Issue by JoeGermuska** [sehmaschine/django-filebrowser#281]
I hope I've got this straight. Let me know if I need to clarify.

I'm investigating deploying django-filebrowser with a site that will use Amazon S3 for storage. I'm piecing together the configuration, and I run into this error:

>TypeError at /admin/filebrowser/browse/
unorderable types: NoneType() < NoneType()

Looking into things, this traces back to trying to order S3 files by `date`. If I change the URL to `http://localhost:8000/admin/filebrowser/browse/?pop=1&o=name`, I get a listing. 

Also, I gather that this specific error is something that is more strict in Python 3 than it was in Python 2? (This is my first project using Python 3)

**Comment by sehmaschine** [comment]
see #40 and #103 about S3.

Note: FileBrowser is not compatible with S3 storage engines due to the missing path variable.

**Comment by JoeGermuska** [comment]
Thanks. Would you consider using Github labels to mark all of the pertinent issues? I can see that several people have looked at this in the past, so I don't want to be cocky, but I'd also like to avoid rewriting everything you've done, so I am going to look into making it work. I'd also love to connect with other folks who are also interested.

**Comment by johndevor** [comment]
+1 @JoeGermuska Would love to see this implemented. Might take a look myself.

**Comment by sehmaschine** [comment]
@JoeGermuska The 2 issues I've mentioned are the only ones, I guess.

**Comment by sehmaschine** [comment]
see #283

**Comment by jcdyer** [comment]
Thanks.  This was helpful.  I'm trying to upgrade a site to django 3, and our filebrowser is broken by this issue.  Changing the default sort fixed the problem.  (We've got it working with S3, but only in the jankiest of ways.
