### ISSUE TITLE
Errors if site.directory value does not end with '/'

### ISSUE THREAD

**Issue by JoeGermuska** [sehmaschine/django-filebrowser#282]
If I configure filebrowser carelessly, e.g.:

```
site.storage = FILEBROWSER_STORAGE
site.directory = 'uploads'
```
For starters, I see an error, "The selected folder does not exist" when I first launch the filebrowser.

However, things basically function, but if I create a new folder in the filebrowser UI, I cannot navigate into the new folder.

It looks like filebrowser constructs a `dir` URL parameter which includes the missing slash, like `http://localhost:8000/admin/filebrowser/browse/?ot=desc&o=date&pop=1&dir=/foo`

This goes away if I change my config to `site.directory='uploads/' but it seems like something which could probably be managed for developers.

**Comment by sehmaschine** [comment]
I've added a warning to the docs. Checking for the trailing slash (e.g. with decorators) is overdone IMO since we need a custom error message and add a translation for that one.
