### ISSUE TITLE
rename TEST IMAGE 000.jpg

### ISSUE THREAD

**Issue by JoeGermuska** [sehmaschine/django-filebrowser#284]
This is minor, but we serve our static files from S3, and it complains when trying to sync the assets from `collectstatic` with this message:

`Invalid key: learncms/filebrowser/img/TEST IMAGE 000.jpg`

If it's all the same to you, renaming that (presumably without spaces) would eliminate some noise from our deployment system.

Thanks for considering it.

**Comment by sehmaschine** [comment]
well, the name has spaces because of the testcases for normalize filename. we'll think about it.

**Comment by sehmaschine** [comment]
@JoeGermuska any special characters (similar to spaces) we could use instead?
