### ISSUE TITLE
png with transparency does not work

### ISSUE THREAD

**Issue by raagin** [sehmaschine/django-filebrowser#291]
I moved to Django 1.8, Grappelli 2.7.1, Filebrowser 3.6.1 and i found, that if i upload png files with transparency, in generated versions, images already without transparency.
In previous environment (Django 1.7, Grappelli 2.6.5, FB 3.5.8) transparency was working.
I've tried to switch to FB 3.5.8 but left django 1.8 and it was working but has produced same result.
Maybe problem somewhere in django 1.8 

I use Pillow 2.9.0 (but i've tried 2.7.0 too)

Thank you

**Comment by sehmaschine** [comment]
so you're saying that it works with django 1.7 and fb 3.5.8, but it does not work with django 1.8 and fb 3.5.8 ... correct? because in that case it does not seem like an fb issue, does it?

**Comment by raagin** [comment]
Yes, true, but the problem still exist. Ok, i will play around

**Comment by raagin** [comment]
I fix the problem by change the code in base.py: 535:
if version.mode not in ("L", "RGB"):
    version = version.convert("RGB")
I added "RGBA" in tuple, and now it is working.
But, why it was working in django 1.7 i don't  understand
