### ISSUE TITLE
Django FileBrowser EXCLUDE Customized  failed

### ISSUE THREAD

**Issue by onebraveman** [sehmaschine/django-filebrowser#294]
I add follow code to project settting files to filter apk files and other settings.
>    # File-browser package settings
    from filebrowser.sites import site
    site.directory = "uploads/"
    FILEBROWSER_EXTENSIONS = getattr(settings, "FILEBROWSER_EXTENSIONS", {
        #'Image': ['.jpg','.jpeg','.gif','.png','.tif','.tiff'],
        #'Document': ['.pdf','.doc','.rtf','.txt','.xls','.csv'],
        #'Video': ['.mov','.wmv','.mpeg','.mpg','.avi','.rm'],
        #'Audio': ['.mp3','.mp4','.wav','.aiff','.midi','.m4p']
        "Apk": ['.apk'],
    })
    FILEBROWSER_EXTENTION_LIST = [] 
    for exts in FILEBROWSER_EXTENSIONS.values():
        FILEBROWSER_EXTENTION_LIST += exts
    FILEBROWSER_EXCLUDE = getattr(settings, 'FILEBROWSER_EXCLUDE', 
                                    (r'_(%(exts)s)_.*_q\d{1,3}\.(%(exts)s)' % {'exts': ('|'.join(FILEBROWSER_EXTENTION_LIST))},))
    
>    # File-browser Extra Settings 
    FILEBROWSER_DEFAULT_SORTING_BY = getattr(settings, "FILEBROWSER_DEFAULT_SORTING_BY", "filesize")
    FILEBROWSER_DEFAULT_SORTING_ORDER = getattr(settings, "FILEBROWSER_DEFAULT_SORTING_ORDER", "desc")
    FILEBROWSER_STRICT_PIL = getattr(settings, 'FILEBROWSER_STRICT_PIL', False)
    FILEBROWSER_SEARCH_TRAVERSE = getattr(settings, "FILEBROWSER_SEARCH_TRAVERSE", True) # traverse all subdirectories
    FILEBROWSER_LIST_PER_PAGE = getattr(settings, "FILEBROWSER_LIST_PER_PAGE", 10)

I have tried:
*    add FILEBROWSER_ for every setting as documentation suggest
*   modify the Django-filebrowser setting.py file, although it works. The method is not a good one as the code belong to the filebrowser package.
*  Debug: add print `EXTENSIONS` messages to Filebrowser `settings` file and project `setting`  file, the result shows global settings takes effect.

Screenshots:
* Settings 
![2015-10-14_160046](https://cloud.githubusercontent.com/assets/14172312/10477977/f49da794-728c-11e5-9acc-c0b666bf966d.png)
![2015-10-14_160113](https://cloud.githubusercontent.com/assets/14172312/10477981/fdb924de-728c-11e5-9b50-26adc23b9ad7.png)
* browse result
![2015-10-14_160307](https://cloud.githubusercontent.com/assets/14172312/10477995/156c90ca-728d-11e5-8a34-6f5fe2d44350.png)

Version:
*    Ubuntu 14
*   django-filebrowser (3.6.1)
*   Django (1.8.3)

Thanks!!

**Comment by sehmaschine** [comment]
a) you should not override the filebrowser settings file (use your project settings file instead).
b) just define FILEBROWSER_EXCLUDE
c) please use the google-group for asking questions. if you think this is a bug, please add more details.

thanks.

**Comment by onebraveman** [comment]
1. I just test the setting by override the filebrowser settings file.
2. I have defined FILEBROWSER_EXCLUDE
3. Thank you for your suggestions

**Comment by sehmaschine** [comment]
2. yes, but the way you defined it has no effect on .apk (it still looks like excluding the thumbnails).
