### ISSUE TITLE
No action menu (Django 1.8)

### ISSUE THREAD

**Issue by trevoriancox** [sehmaschine/django-filebrowser#295]
With django-filebrowser 3.6.1 and Django 1.8, I do not have an action menu. (i.e. I can't delete or do anything else with the list of images). View, search, filter, new folder, and upload are working.

I tried with and without:

```
from filebrowser.actions import flip_horizontal, flip_vertical, rotate_90_clockwise, rotate_90_counterclockwise, rotate_180
site.add_action(flip_horizontal)
site.add_action(flip_vertical)
site.add_action(rotate_90_clockwise)
site.add_action(rotate_90_counterclockwise)
site.add_action(rotate_180)
```

**Comment by sehmaschine** [comment]
these actions are already assigend with a default filebrowser site.

**Comment by trevoriancox** [comment]
Yes. I was just making it clear that I wasn't just missing the add_action's.

**Comment by sehmaschine** [comment]
just tested – works fine with my setup.

you know that these actions are only available with the changeform (not the changelist), right? I'm just asking because you refer to "the list of images".

**Comment by trevoriancox** [comment]
Sorry, I'd assumed that the "actions" were Django admin "actions" on the changelist.

And I hadn't seen the changeform because the changelinks weren't visible due to 

> li.grp-change-link { display: none }

which I'd set because I found "change" links redundant in my Grappelli dashboard.

Thanks!
