### ISSUE TITLE
Extending filebrowser

### ISSUE THREAD

**Issue by andybak** [sehmaschine/django-filebrowser#297]
I've got some ideas in improving the extensibility of Filebrowser (basically borrowing more ideas from contrib.admin)

1. An equivalent to list_display which accepts a callable and passes in the file object for each row. This would make it easy to incorporate EXIF and other metadata
2. Making the templates more modular so that overriding small parts of the list or detail view is easier.

Are these of interest?

One thing that concerns me is the overhead of maintaining changes on both this and the no-grappelli branch. It strikes me that one side-effect of (2) would be to allow the separation of the Grappelli specific parts from the common parts - this would possibly allow merging of the two versions of filebrowser - or at least make it much simpler for the non-grappelli version to track your version.

**Comment by sehmaschine** [comment]
generally speaking, these updates are of interest. but I think we should handle the FileBrowseUploadField first, do a release and tackle the other improvements afterwards.

concerning the no-grappelli branch: to be honest, my interest in dealing with this stuff is very limited. I'd say that we currently only accept grappelli-compatible updates.

**Comment by andybak** [comment]
> my interest in dealing with this stuff is very limited. I'd say that we currently only accept grappelli-compatible updates.

My filebrowser upload work may or may not be grappelli compatible - I've got no way of testing short of installing grappelli and I don't really have the time or motivation to do that. I was hoping you would handle that side of it.

I'd rather that the two forks didn't diverge but being Grappelli-specific means that non-Grappelli users are unlikely to contribute. 

My hunch is that some small architectural changes could lead filebrowser to a place where it was much more template agnostic with the side-effect of improving it's extensibility all-round. Would you at least like me to look into this or would I be better off working solely on the no-grappelli fork?

**Comment by sehmaschine** [comment]
I'm not exactly sure which updates we are discussing right now ... concerning the FileBrowseUploadField and list_display, I'll check the compatibility with grappelli (if you're able to either send a PR or link to files within the no-grappelli branch).

Concerning template updates, I don't think I'm able to maintain a no-grappelli version. That said, I'm interested in improving the extensibility. It's probably best if you start working with the no-grappelli fork and I'll figure out a possible implementation afterwards.

**Comment by sehmaschine** [comment]
closing this for now since no further comments are given. feel free to reopen is you're still interested in dealing with this issue.

**Comment by andybak** [comment]
I will do.

It's worth noting that I'm maintaining as an external app: https://github.com/DjangoAdminHackers/django-filebrowser-browse-upload-field

and using it in production on multiple sites. Doing it externally resulted in a touch of code duplication but gave me the freedom to be opinionated regarding my use-case and avoid handling a few edge-cases that didn't apply to me.
