### ISSUE TITLE
admin thumbnail and _versions folder duplicate

### ISSUE THREAD

**Issue by V1ce** [sehmaschine/django-filebrowser#298]
Hi,

I got strange problems with versions.When a versions of image is created in admin interface or in a model method (self.img.version_generate('medium')) an other "_versions" folder is created under the base "_versions" and thumbnail are duplicated, its difficult to explain ill post my media folder tree for example 

Django 1.8.6
grappelli : 2.7
Filebrowser 3.6.2

settings : 

    MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
    MEDIA_URL = '/media/'
    FILEBROWSER_VERSIONS_BASEDIR = 'img/_versions/'
    from filebrowser.sites import site
    site.directory = "img/"
    FILEBROWSER_ADMIN_VERSIONS = ['thumbnail', 'small', 'medium', 'big', 'large']
    FILEBROWSER_ADMIN_THUMBNAIL = 'admin_thumbnail'

tree : 

    media/
        img/
            _versions/
                _versions/
                    photo/
                        P1010503_admin_thumbnail_admin_thumbnail.jpg
                        P1010503_medium_admin_thumbnail.jpg
                        P1010503_small_admin_thumbnail.jpg
                        P1010503_medium_small.jpg
                        P1010503_medium_medium.jpg
                photo/
                    P1010503_admin_thumbnail.jpg
                    P1010503_small.jpg
                    P1010503_medium.jpg
            photo/
                 P1010503.jpg

Thanks

**Comment by sehmaschine** [comment]
try to put the versions dir outside the directory path

**Comment by luizrrodrigues** [comment]
Still happens, when select select a version in FielBrowserField (not original) its will create a duplicate _versions folder.

Filebrowser 3.7.2

**Comment by sehmaschine** [comment]
@luizrrodrigues`FILEBROWSER_VERSIONS_BASEDIR` is outside of `site.directory`, right?

**Comment by luizrrodrigues** [comment]
@sehmaschine Yep:
FILEBROWSER_DIRECTORY = 'photos/'
FILEBROWSER_VERSIONS_BASEDIR = '_versions/'
