### ISSUE TITLE
Limiting access to uploads in FileBrowseField's widget [proposal]

### ISSUE THREAD

**Issue by SebasSBM** [sehmaschine/django-filebrowser#299]
It would be useful having an optional parameter to limit access to uploaded content through `FilebrowseField` in models. So, for example, making that every user can only upload and see their own files, but not the ones belonging to others.

I have noticed that django-filebrowser 3.6.1 doesn't have this feature yet. Through it seems that implementing such a feature would not be easy, it would be very useful to have it in the next version.

**Comment by sehmaschine** [comment]
how would you handle files uploaded via FTP then?
besides, I might not only be able to browse my own files but also files within my "group".

to me, this sounds like building a permissions system, which is out of scope.

**Comment by SebasSBM** [comment]
For now I am only able to show an abstract idea about it:
    * It would not be necessarily a Django permission. I would rather implement it as a FileBrowseField property instead, so it would only affect to a specific field.
    * If the property was set to True, then files would be uploaded to (FILEBROWSER_DIRECTORY + 'uploads/user_name/'), or (MEDIA_ROOT + 'uploads/user_name/'). In other words, a subfolder of the folder that django-filebrowser would normally use.
    * With this setting on, users would only see what's uploaded in their folder, so they would not be able to access the parent folder, nor even see it.

This is the abstract idea about how I would implement it.

**Comment by sehmaschine** [comment]
in my opinion, this is currently out of scope. however, feel free to send a PR and we'll check a possible implementation.
