### ISSUE TITLE
Django-filebrowser incorrect image url

### ISSUE THREAD

**Issue by mariuszstr** [sehmaschine/django-filebrowser#302]
I'm using FileBrowser for upload image files. In my settings.py I set

    from filebrowser.sites import site
    site.storage.location =  SITE_ROOT + "/static/memes_images/"

and filebrowser uploads files to this directory correctly. But the problem is with image Thumbnail in filebrowser file list. Thumbnails are not shown,
because It tries to show it from link `http://localhost:8000/admin/filebrowser/browse/name.jpg`. The correct link is `hhttp://localhost:8000/static/memes_images/name.jpg`. I try to set it in `settings.py`:

    site.storage.url = "http://localhost:8000/static/memes_images"

but when I set it, FileBrowser uses empty string as image url instead this `http://localhost:8000/static/memes_images/name.jpg`.

How can I change the image url used by FileBrowser?  Is it FileBrowser bug, or I do something wrong?

**Comment by sehmaschine** [comment]
sorry, but I'm not able to follow. first off, using the static directory is not a good idea (use media instead). the thumbnails are stored with your versions directory (so I guess you need to check your settings).
