### ISSUE TITLE
convert_filename erases non-ascii but valid alphabetical character in non-latin encodings

### ISSUE THREAD

**Issue by Romeno** [sehmaschine/django-filebrowser#304]
If NORMALIZE_FILENAME is set to True
filebrowser.utils.convert_filename erases all non-ascii characters from the filename. If name of the file is in Russian for example it is erased completely.

v = unicodedata.normalize('NFKD', six.text_type(v)).encode('ascii', 'ignore').decode('ascii')

Filebrowser v3.5.8

**Comment by sehmaschine** [comment]
any idea on how to solve this? a testcase would be nice as well.

**Comment by Romeno** [comment]
I did not dig into the solution I just turned NORMALIZE_FILENAME option off
