### ISSUE TITLE
Upload page, extension setting cause js errors

### ISSUE THREAD

**Issue by pinkdawn** [sehmaschine/django-filebrowser#305]
I'm Using django 1.9, filebrowser 3.6.2, and python 2.7.2. Plain install, default config.

In upload page, I get an empty page, and a js error:

` allowedExtensions: [&#39;.jpg&#39;, &#39;.jpeg&#39;, &#39;.gif&#39;, &#39;.png&#39;, &#39;.tif&#39;, &#39;.tiff&#39;, &#39;.pdf&#39;, &#39;.doc&#39;, &#39;.rtf&#39;, &#39;.txt&#39;, &#39;.xls&#39;, &#39;.csv&#39;, &#39;.docx&#39;, &#39;.mov&#39;, &#39;.mp4&#39;, &#39;.m4v&#39;, &#39;.webm&#39;, &#39;.wmv&#39;, &#39;.mpeg&#39;, &#39;.mpg&#39;, &#39;.avi&#39;, &#39;.rm&#39;, &#39;.mp3&#39;, &#39;.wav&#39;, &#39;.aiff&#39;, &#39;.midi&#39;, &#39;.m4p&#39;],`

Seems like the extension are encode `'` as `&#39;`, which cause js error and blocks render of rest page.

Any idea I can bypass this js error? Like put something in my setting to override the `allowedExtensions` ??

**Comment by smacker** [comment]
As I can see you have only one option how to fix it for Django 1.9, fork it and make this change: https://github.com/smacker/django-filebrowser-no-grappelli/commit/ee781b2a4a1ecd58808bb73f515345d68b2727a2#diff-4fecb91e1ac1257be16a649277b0aa6aR158

**Comment by pinkdawn** [comment]
@smacker thanks, I switch to `django-filebrowser-no-grappelli`, and make a minor change at `filebrowser\templates\filebrowser\upload.html`, change `django.jQuery` to `jQuery`, now it works!

**Comment by smacker** [comment]
@pinkdawn sorry, but why do you need this change about jQuery? I don't use django 1.9 but guys report that everything works https://github.com/smacker/django-filebrowser-no-grappelli/issues/18#issuecomment-188908510

**Comment by sehmaschine** [comment]
filebrowser 3.6.x is not compatible with django 1.9 – therefore I'm closing this one (besides, I guess this ticket is not relevant anymore since you switched to filebrowser-no-grappelli anyway). feel free to reopen this ticket with additional details.
