### ISSUE TITLE
FILEBROWSER_EXTENSIONS is not working

### ISSUE THREAD

**Issue by v-hunt** [sehmaschine/django-filebrowser#307]
When I set FILEBROWSER_EXTENSIONS in settings.py, uploading files feature isn't working at all (see screenshot)

For instance, if I set the default settings:
```python
    FILEBROWSER_EXTENSIONS = {
        'Image': ['.jpg', '.jpeg', '.gif', '.png', '.tif', '.tiff'],
        'Document': ['.pdf', '.doc', '.rtf', '.txt', '.xls', '.csv', '.docx'],
        'Video': ['.mov', '.mp4', '.m4v', '.webm', '.wmv', '.mpeg', '.mpg', '.avi', '.rm'],
        'Audio': ['.mp3', '.wav', '.aiff', '.midi', '.m4p']
    }
```
![filebrowser-bug](https://cloud.githubusercontent.com/assets/17613599/13848491/be07bae2-ec5a-11e5-97cf-3d07898b4f70.png)

As you can see, there is no 'Upload file' button and help block is unactive.

There is no errors in console. All other settings options seem to work fine.
Version is 3.6.4

**Comment by sehmaschine** [comment]
which django version?

**Comment by v-hunt** [comment]
Hi, Patrick,
Thank you for quick response. Django version is 1.8.8

**Comment by sehmaschine** [comment]
that's strange ... so when you remove that setting, the upload is working?

**Comment by v-hunt** [comment]
Yep, you're right. When you remove that setting, the upload is working. And all other settings don't conflict except this one. I now that it sounds odd...

Another useful information (maybe useful): I use non-standart admin url (/gs-admin instead of admin). My urls setting look like:

```python
    url(r'^gs-admin/filebrowser/', include(site.urls)),  # filebrowser url
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^gs-admin/', include(admin.site.urls)),
```

**Comment by sehmaschine** [comment]
well, hard to say ... eventually, it should not make a difference whether you set FILEBROWSER_EXTENSIONS with your own settings-file or use the standard EXTENSIONS (with your example, it's exactly the same).

I don't see a bug here. But if you're able to add more details (or even send a PR), I'm happy to take a look.

**Comment by v-hunt** [comment]
When I have a little bit of free time (later), I'm going to make fresh installation of django=1.8.8, django-grappelli==2.7.3 and  django-filebrowser==3.6.4 and to have a look if that strange error is still exist. Possibly there is some conflict with other packages that I use for time being (But I understand that there is a very low probability of that conflict). Also I think it worth then to make some other fresh installation with different versions of Filebrowser, Django and Grappelli. After I do that I will notify you here. 

Also it would be great if somebody has the same error and leave a note here (or if he uses the same versions of packages and doesn't have an error, it would be good to know as well :)

If you need some additional information from me, I'm glad to share it with you. Just ask me what you need. 

PS: What does "PR" mean? Sorry, English isn't my native language...

**Comment by sehmaschine** [comment]
PR means pull request. But your approach (fresh installations) sounds fine for now.

**Comment by v-hunt** [comment]
Ok, I will try to make fresh installation first. Then it make sense to discuss it. I the error will still occur, I can provide you access to the code on Bitbucket, if you wish (I mostly Bitbucket user)

**Comment by sehmaschine** [comment]
closing this for now. please reopen if the issue still exists.
