### ISSUE TITLE
FileBrowseField does not return FileObject

### ISSUE THREAD

**Issue by michalwerner** [sehmaschine/django-filebrowser#310]
I don't know if it's intended behavior, but:
documentation says, that ``FileBrowseField`` returns ``FileObject``, but in fact it returns ``str``.
After I manually reverted f0e02c4204d857db14ec81830ae0ceede18fef7d, it returns ``FileObject`` as expected, so it seems to be the reason.
Correct me if I'm wrong: either documentation should be updated, or mentioned commit has some unwanted impact on ``FileBrowseField``.

**Comment by sehmaschine** [comment]
good point. thanks for the PR.

**Comment by fgmacedo** [comment]
Hi guys! The code has been merged. I think that this issue can be closed.

**Comment by sehmaschine** [comment]
It's not merged with master yet (therefore the ticket is still open).
