### ISSUE TITLE
Can't upload files through tinymce editor.

### ISSUE THREAD

**Issue by old-willow** [sehmaschine/django-filebrowser#312]
Since there is no anymore Filebrowser Google Group I have decided to write here my question that I posted already on stackoverflow too:
[question on stackoverflow](http://stackoverflow.com/questions/36474785/django-filebrowser-tinymce-cant-upload-images)

**Tests:**  
```
$: python manage.py test filebrowser
/home/user/venv/py2_django_19_4/local/lib/python2.7/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/user/venv/py2_django_19_4/local/lib/python2.7/site-packages/filebrowser/fields.py:200: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  class FileBrowseUploadField(CharField):

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Version:**
django-filebrowser: 3.6.4, grappelli: 2.7.3, Django: 1.9.4

Everything is working except file upload. I can see already uploaded files through ImageField but I want to upload file with FileBrowseField and HTMLField too. There is no "UPLOAD A FILE" button. 
Here is the link on what I get when I want to upload an image with tinymce editor in my field:
[Link](https://gyazo.com/175028ba6630d94f1ddd7148697775ab)

One more thing is that when I inspect the window there is an error message in the console:
`Uncaught SyntaxError: Unexpected token &                        127.0.0.1/:97`

Thanks in advance.

**Comment by sehmaschine** [comment]
Here's the link to the Google Group:
https://groups.google.com/forum/#!forum/djangofilebrowser
