### ISSUE TITLE
Add support for custom crops 

### ISSUE THREAD

**Issue by fgmacedo** [sehmaschine/django-filebrowser#313]
Hi!

I want to adapt something like [django-image-cropping](https://github.com/jonasundderwolf/django-image-cropping) is for `django-thumbnails`, but for use with `django-filebrowser`.

> django-image-cropping is perfect when you need images with a specific size for your templates but want your users or editors to upload images of any dimension. It presents a selection with a fixed aspect ratio so your users can't break the layout with oddly-sized images.

> The original images are kept intact and only get cropped when they are displayed. Large images are presented in a small format, so even very big images can easily be cropped.

![crop area on admin](https://camo.githubusercontent.com/380fc9cf61addb461fbaefd91c39ec07e5f80f88/687474703a2f2f7777772e6a6f6e6173756e64646572776f6c662e64652f6d656469612f696d616765732f646a616e676f5f696d6167655f63726f7070696e675f6578616d706c652e706e67)

We will need something like this:

1. A new field that stores the crop edges as a box, the field definition should contain the desired final size, like in `VERSIONS`. This can be a [CharField](https://github.com/jonasundderwolf/django-image-cropping/blob/master/image_cropping/fields.py#L27) with a custom widget.
2. A new function that crops an image using a box definition, like [crop_corners](https://github.com/jonasundderwolf/django-image-cropping/blob/master/image_cropping/thumbnail_processors.py#L8).
3. Some [css, js files](https://github.com/jonasundderwolf/django-image-cropping/tree/master/image_cropping/static/image_cropping) to handle crop on admin.
4. Add some way to extend `FileObject.version_generate` using a custom function that generate versions that are not stored into the `settings.VERSIONS`, but in the calling context.

I think that steps 1 to 3 can be in another project, as `django-image-cropping` is to `django-thumbnails`, if you don't want to provide this functionality out of the box. 

The 4th step is required to be in `django-filebrowser` to allow the use of `FileObject` with custom `version_generate` pipeline.

What do you think? Can you provide me some guidance on where to work in order to get this into `django-filebrowser`?

Best regards!

**Comment by sehmaschine** [comment]
we had this discussion before and I'm -1 on integrating this. IMO automatic cropping never leads to a satisfying result. Instead, I would recommend that editors upload images with the correct aspect ratio and VERSIONS are being used.

**Comment by fgmacedo** [comment]
@sehmaschine Ok. But only to verify that I was clear: This is not "automatic cropping", It is an option to allow uploads of images without the correct aspect ratio and the option to mark the correct image area WITH THE CORRECT ASPECT RATIO on admin. 

Why? Because with de same uploaded image, we can generate crops with the correct aspect ratio, but from different areas of the image. How to upload the correct aspect ratio of an **source** image that has to be used as two versions, one 80x80 and another 250x50? The automatic behavior that VERSIONS actually does is to crop without allowing the admin to choose from an image area. This can result in one of those crops being not optimal, even if the uploaded image aspect ratio is the correct for one of the versions.

**Comment by sehmaschine** [comment]
@fgmacedo sorry, I misunderstood that proposal. makes much more sense now and I can actually see the usecase. that said, it seems like a major update and unfortunately I currently don't have the spare time to help with guidance/advice. but if you wanna submit a PR, I'm happy to review.

**Comment by fgmacedo** [comment]
@sehmaschine No problem! Nice! I'll try to accomplish this and send you a PR.

**Comment by sehmaschine** [comment]
@fgmacedo thanks. please use branch stable/3.7.x instead of master, so I can easily merge (and rollback).
