### ISSUE TITLE
instance delete - generated versions remain

### ISSUE THREAD

**Issue by chemcnabb** [sehmaschine/django-filebrowser#316]
Is there a tool for removing only the generated image versions associated to an model instance, rather than a cmd tool for cleaning/generating all?  

I'm currently using:  

instance.image.version_generate(VERSIONS).delete()

in a post_delete signal, which feels a bit 'smelly'.

Is there a proper recommended way?  (I have gone over the docs, nothing immediately stands out.)

**Comment by sehmaschine** [comment]
sorry for the late reply. there is currently not built-in tool or command in order to achieve this. if you send a tested PR, I'm happy to review.
