### ISSUE TITLE
Directory scoped to content

### ISSUE THREAD

**Issue by felixSchl** [sehmaschine/django-filebrowser#319]
Tests: OK
Version: FileBrowser 3.5.4, Grappelli 2.7.3, Django 1.8

This is more of question, really. I've been over the source code (especially `sites.py`) and
am wondering how to best use `django-filebrowser` to scope uploading to a directory based
on content. So rather than having a single `/browse` url, it would be scoped to some content.
Because `directory` is a member variable of `FileBrowserSite`, it seems I cannot set it from a
variable in the querystring in `urls.py` (unless I mutate the object)

I am aware the version of the project I am running is ancient, but I compared it to the latest sources
and nothing in that respect seems to have changed, but please correct me if I am wrong.

Thank you

**Comment by sehmaschine** [comment]
I'm not sure if this is possible without modifying sites.py ... besides, please use the google-group for asking questions.
