### ISSUE TITLE
Using FileBrowseFormField in admin inline

### ISSUE THREAD

**Issue by felixSchl** [sehmaschine/django-filebrowser#320]
Tests: OK
Version: FileBrowser 3.5.4, Grappelli 2.7.3, Django 1.8
(i've also tried with 3.7.1)

When I define a form for an inline:

```python
class ProjectDownloadForm(ModelForm):
    file = FileBrowseFormField()

class ProjectDownloadInline(admin.TabularInline):
    model = ProjectDownload
    form = ProjectDownloadForm
```

Then the field just renders as a regular `CharField`. Could this have to do with JS not finding the element or something?

Edit: to clarify, this works:

```python
class ProjectDownloadForm(ModelForm):
    pass
    #file = FileBrowseFormField()

class ProjectDownloadInline(admin.TabularInline):
    model = ProjectDownload
    form = ProjectDownloadForm
```

**Comment by sehmaschine** [comment]
Do you use a FileBrowseField with your model?

**Comment by felixSchl** [comment]
Yes

**Comment by sehmaschine** [comment]
in that case, I don't understand what you're doing with the ModelForm ... any specific reason you need to define a FileBrowseFormField?

**Comment by felixSchl** [comment]
So I can overwrite the directory or site parameter. Related to #319

**Comment by sehmaschine** [comment]
Now I see. Sorry, but I guess I'm not able to help with this issue ... I've never tried using the formfield this way. Theoretically speaking, it should work like you're doing it.

**Comment by felixSchl** [comment]
Would it help if I created a failing test case or an example repo?

**Comment by sehmaschine** [comment]
It would help if you're trying to debug the issue and add more detailed information here.

Are you able to add that case to the existing tests? If so, you're already pretty close to figure out what's going on IMO.

**Comment by felixSchl** [comment]
Widget needs to be explicitely passed:

```
projects_filebrowse_site = FileBrowserSite(
    name='projects',
    app_name='foo',
)
projects_filebrowse_site.directory = settings.PROJECT_FILES_DIRECTORY

class ProjectDownloadForm(ModelForm):
    file = FileBrowseFormField(
        site=projects_filebrowse_site,
        widget=FileBrowseWidget(
            attrs={
                'filebrowser_site': projects_filebrowse_site,
            },
        )
    )
```
