### ISSUE TITLE
file browser permission didn't work correct

### ISSUE THREAD

**Issue by sj-sadeghi** [sehmaschine/django-filebrowser#322]
hi ...
excuse me. i'm poor in english.
i use file browser in my project, but file browser permission didn't work correct. 
when i create a limit user without any file browser permission(add,change,de;ete). this user cannot see the file browser app in django admin but, if this user type in url .../admin/filebrowser/browse/ . this user can see file browser app. 

i test this on :
`python 2.7`

----------------

django 1.8
with
file browser 3.6.4

----------------
django 1.9
with
file browser 3.7.1

**Comment by sehmaschine** [comment]
there is no permission system with the filebrowser ...
you could check this pull request (https://github.com/sehmaschine/django-filebrowser/pull/264) though.

**Comment by sj-sadeghi** [comment]
thanks for reply, but this solution didn't work for django 1.9
