### ISSUE TITLE
Support for Grappelli 2.9.x and Django 1.10.x?

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-filebrowser#326]
Trying to update my Dev setup to verify Grapelli changes, I ran into a really neat problem with File Browser!

PIP made me update it to V9.  Then a PIP CHECK told me File Browser was not recommended for my new Grappelli version.  So I told PIP to update FB - thinking there would be a new version with updated requirements specs.  And it DOWNGRADED my Grappelli back to 2.8!!!  Below is the console session.

```
(py27dj110)rcooke@developer1:~/source/GNVO/django-DEV$ pip check
django-filebrowser 3.7.2 has requirement django-grappelli<2.9,>=2.8, but you have django-grappelli 2.9.1.


(py27dj110)rcooke@developer1:~/source/GNVO/django-DEV$ pip show django-filebrowser
Name: django-filebrowser
Version: 3.7.2
Summary: Media-Management with Grappelli
Home-page: http://django-filebrowser.readthedocs.org
Author: Patrick Kranzlmueller, Axel Swoboda (vonautomatisch)
Author-email: office@vonautomatisch.at
License: BSD
Location: /home/rcooke/.virtualenvs/py27dj110/lib/python2.7/site-packages
Requires: django-grappelli


(py27dj110)rcooke@developer1:~/source/GNVO/django-DEV$ pip install --upgrade django-filebrowser
Requirement already up-to-date: django-filebrowser in /home/rcooke/.virtualenvs/py27dj110/lib/python2.7/site-packages
Collecting django-grappelli<2.9,>=2.8 (from django-filebrowser)
  Downloading django_grappelli-2.8.3-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 594kB/s 
Installing collected packages: django-grappelli
  Found existing installation: django-grappelli 2.9.1
    Uninstalling django-grappelli-2.9.1:
      Successfully uninstalled django-grappelli-2.9.1
Successfully installed django-grappelli-2.8.3
(py27dj110)rcooke@developer1:~/source/GNVO/django-DEV$ 
```

**Comment by ugoertz** [comment]
Trying to advance this issue a little further:

The only problem I was able to find is the way the optional argument for the [fb_version_generate](http://django-filebrowser.readthedocs.io/en/latest/versions.html#cmdoption-arg-fb_version_generate) management command is defined. (The optparse syntax was dropped in Django 1.10 [in favor of argparse](https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/#accepting-optional-arguments).)

This causes the only failure in the test suite, and I did not notice any other problems beyond that.

Do you think I am missing something?

Thanks for your work!

**Comment by groundupnews** [comment]
I hope this helps: I moved my production site over to 1.10 today using
Filebrowser 3.7.2. I tested it quite a bit before doing so. All the
critical functionality seems to work just fine. While my site doesn't use
all Filebrowser's functionality, I've encountered no problems at all.
