### ISSUE TITLE
FileBrowseField in Inlines

### ISSUE THREAD

**Issue by dteskera** [sehmaschine/django-filebrowser#327]
if you have a FileBrowseField in your inlines and after clicking on add more inlines you cant browse for images with those newly generated inlines.

problem is that after clicking on add more inlines django admin is cloning the prefixed empty form and replacing \_\_prefix\_\_ with the actual next id but only in some predefined places like id attributes, but it isn't replacing it in a href attribute where your javascript code resides.

cant easily make a pull requests since i have already forked the no-grappelli fork but the following change works for me.

templates/custom_field.html:2
before
```
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField{% if final_attrs.class %} {{ final_attrs.class }}{% endif %}" name="{{ final_attrs.name }}" value="{{ value.path }}" {% for k, v in final_attrs.data_attrs.items %}{{k}}="{{v}}" {% endfor %}/><a href="javascript:FileBrowser.show('{{ final_attrs.id }}', '{{ url }}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory|urlencode|urlencode }}{% endif %}{% if final_attrs.format %}&amp;filter_type={{ final_attrs.format }}{% endif %}');" class="fb_show"></a>
```
after
```
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField{% if final_attrs.class %} {{ final_attrs.class }}{% endif %}" name="{{ final_attrs.name }}" value="{{ value.path }}" {% for k, v in final_attrs.data_attrs.items %}{{k}}="{{v}}" {% endfor %}/><a href="#" onclick="FileBrowser.show($('input[type!=hidden]', $(this).parent())[0].id, '{{ url }}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory|urlencode|urlencode }}{% endif %}{% if final_attrs.format %}&amp;filter_type={{ final_attrs.format }}{% endif %}');" class="fb_show"></a>

```
i guess its the same with custom_upload_field.html

**Comment by sehmaschine** [comment]
I'm not able to reproduce this. Images with Inlines work fine with my tests.

**Comment by dteskera** [comment]
you're right. the issue was with the no-grappelli fork. you're doing it right in grappelli.

**Comment by pyMan** [comment]
I have the same problem described by @dteskera (with django-filebrowser 3.12.1 and grappelli 2.13.3 and django 2.2.9).

Post rendering `{{ final_attrs.id }}` is not replaced inside the _href_ by some js like done for the input ID, so you need to change the `href` to `onclick` and get the value dynamically
