### ISSUE TITLE
Broken edit link in filelisting when searching in sub-folders

### ISSUE THREAD

**Issue by marco-primiceri** [sehmaschine/django-filebrowser#329]
The [Change link in the filelisting template](https://github.com/sehmaschine/django-filebrowser/blob/master/filebrowser/templates/filebrowser/include/filelisting.html#L130) populates the `dir` parameter using `query_string`, this works fine when the search result is in the current folder but creates an invalid URL when the result is in a sub-folder.

### Example

Given this tree structure:
```
brands
  - all_brands_logo.jpg
  - acura
     - logo.jpg
  - alfa_romeo
     - logo.jpg
  - aston_martin
  - ...
```
Searching for `logo` within the `brands` folder will return the following:
Current URL: /admin/filebrowser/browse/?q=logo&dir=brands

**Filename**: logo_brands_diagram.jpg 
**Folder**: brands
**Change link**: /admin/filebrowser/detail/?q=logo&dir=brands&filename=all_brands_logo.jpg ==> OK

**Filename**: logo.jpg 
**Folder**: brands/acura
**Change link**: /admin/filebrowser/detail/?q=logo&**dir=brands**&filename=logo.jpg ==> **BROKEN**

**Comment by sehmaschine** [comment]
fixed with stable/3.10.x
