### ISSUE TITLE
Fix for Error on field.py in lines 41, 161 (build_attrs function) on Django 1.11

### ISSUE THREAD

**Issue by ccapudev** [sehmaschine/django-filebrowser#330]
v3.7.2:
final_attrs = self.build_attrs(attrs, **type=self.input_type, name=name**)
Fix:
final_attrs = self.build_attrs(attrs, **extra_attrs={"type":self.input_type,"name":name}**)

Django 1.11 has deleted ****kwargs** on this function.

**Comment by crack-king** [comment]
Is there any hope for an update? This project hasn't been updated since august 2016...

**Comment by sehmaschine** [comment]
yes, there is hope.

**Comment by crack-king** [comment]
Would be great if you would manage to support django 1.11 :)

**Comment by sehmaschine** [comment]
that´s the plan.

**Comment by crack-king** [comment]
any estimates?

**Comment by sehmaschine** [comment]
nope, sorry. as soon as we find the time to work on it.
