### ISSUE TITLE
Cant upload. Can only browse

### ISSUE THREAD

**Issue by glennpierce** [sehmaschine/django-filebrowser#332]
Hi

I am using django 1.9
and grappelli 2.91

I have followed the instructions but I can't seem to upload images with filebroswer.

If I go to the browse page I can see images in the directory but no means to upload a new image.
The screen looks like

https://www.dropbox.com/s/1q8o1je529qc2ky/browse.png?dl=0

Upload screen looks like this. (Upload link greyed out)
https://www.dropbox.com/s/1q8o1je529qc2ky/browse.png?dl=0

Has anyone seen this?  I don't seem to see any errors

**Comment by sehmaschine** [comment]
If your screen looks like this, there are js/css files missing. Please
check your setup (serving static files).

2017-04-11 11:44 GMT+02:00 Glenn Pierce <notifications@github.com>:

**Comment by glennpierce** [comment]
Ah I had overridden  /templates/admin/
Now I have to remember why :)
