### ISSUE TITLE
Potential contribution: filebrowser-browse-upload

### ISSUE THREAD

**Issue by andybak** [sehmaschine/django-filebrowser#333]
https://github.com/DjangoAdminHackers/django-filebrowser-browse-upload-field

We find this incredibly useful and it's become our default replacement for FileField and ImageField on all projects. It's been in production for over a year now and is fairly solid.

I'd be curious to see if it's useful to other people (or indeed maybe even worthy of being added to this project). It's based on the filebrowse field but I think it gives a better overall user experience for typical use-cases.

1. It's not tested on the 3.7 branch
2. It's not tested on the main django-filebrowser repo - I use the no-grappelli fork
3. It's not been tested outside our standard CMS deployment - there might be a dependency somewhere that I've not thought about.

**Comment by int-ua** [comment]
Can it be used just for widget, without changing field type?

**Comment by andybak** [comment]
So - you are using django-filebrowser?

Why does it matter that the field type changes? The underlying database representation is the same.

**Comment by int-ua** [comment]
1. Yes.
2. Because we are already using a custom subclassed ImageField. And I'd like to make less modifications, I'm not sure why field type change needed. Because it allows some per-field settings? Can't they in theory be specified on the widget itself?

**Comment by sehmaschine** [comment]
@andybak you never added a PR. should we close this issue?

**Comment by sehmaschine** [comment]
see also #236

**Comment by sehmaschine** [comment]
closing this since no PR has been made.
