### ISSUE TITLE
Incorporate user permissions for uploaded files

### ISSUE THREAD

**Issue by karol-bujacek** [sehmaschine/django-filebrowser#334]
Hello. I’ve recently tried django-filebrowser (no-grappelli fork, but I think this is better place for such a question) and I’m really missing feature for multi-user environments. I have many users registered in my django based application and I want to allow them to upload and embed images into their articles. However, I’m not able to specify the relationship between django user and uploaded file – any user can edit/delete any file, which is undesirable. (Using somebody elses files might be nice, but update/delete must be forbidden.)

Do you have any plans to add functionality which somehow incorporate user permissions for uploaded files? May such a feature be useful for somebody else expect me?

**Comment by sehmaschine** [comment]
IMO it´s a useful feature for others as well. But we don´t have any plans to implement this (since we personally don´t need it). But I'm happy to review a PR.

I'm still closing this for now since it´s not referring to an actual issue.
