### ISSUE TITLE
FileBrowseField - Adding programmatically

### ISSUE THREAD

**Issue by yoerivdm** [sehmaschine/django-filebrowser#335]
Hi, I'm using FileBrowseField on some models. 
Need to create a custom interface to add images that are already defined as FileBrowseFields.

This is the model:
```
class ArtworkPhoto(models.Model):
   title = models.CharField(max_length=200, verbose_name='Omschrijving', blank=True)
   photo = FileBrowseField("Image", max_length=200, directory="artwork/",
                        extensions=[".jpg", ".png"], blank=False, null=False)
   artwork = models.ForeignKey(Artwork, null=False, verbose_name='kunstwerk')
```

How can I create this model and save an uploaded photo with it (request.files)?

Thanks!

**Comment by sehmaschine** [comment]
I'm sorry, but I don´t fully understand that question. Besides, please use the google-group for asking questions.
