### ISSUE TITLE
Make dynamic site.directory dependent on request.user

### ISSUE THREAD

**Issue by fnahuelc** [sehmaschine/django-filebrowser#336]
The idea is that each user accesses a different folder, being able to upload their files separately without being able to view or modify the files of other users.

For this I must constantly modify the settings (site.directory) according to the request. 
Example: uploads/<request.user.id>/

I'm doing something similar to this solution: https://stackoverflow.com/questions/21794867/dynamic-image-upload-browsing-path-for-django-tinymce
But I also need to extend all get_urls methods to make sure that IDs are not crossed from one user to another.

This seems to work but I wonder if there is a better solution.

Thank you!

**Comment by sehmaschine** [comment]
Closing this since there are no replies.
I'm also not able to propose a better/working solution, since we never had that issue.

Besides, please use the google-group for questions.
