### ISSUE TITLE
Compatible with last grappelli

### ISSUE THREAD

**Issue by sharifzadesina** [sehmaschine/django-filebrowser#340]
Hi
As of [this](https://github.com/sehmaschine/django-grappelli/commit/cf9400538b9d09216d9777905c93729dd3bd996b) commit, we have a namespace for all grappelli tables, so we need to add that namespace to also filebrowser tables.

**Comment by sehmaschine** [comment]
Yes, we´ll fix that once the grappelli version has been released (which is not the case yet).

**Comment by sharifzadesina** [comment]
@sehmaschine I did a PR for these two issues, check it please. #342

**Comment by sehmaschine** [comment]
Thanks for that! But we still need to wait for the grappelli release.

**Comment by sharifzadesina** [comment]
OK, but I thought the branches are for new changes and tags (versions) are for using by developers, so we can commit any upcoming features to branches. then after grappelli release, we can create new tag (version).

**Comment by sehmaschine** [comment]
Yep, you´re absolutely right. I didn't see that you're targeting the branch with your PR. Sorry!

**Comment by sehmaschine** [comment]
fixed with stable/3.10.x
