### ISSUE TITLE
New CHANGE_FILENAME setting

### ISSUE THREAD

**Issue by sharifzadesina** [sehmaschine/django-filebrowser#344]
Hi
How about adding a new setting for changing filenames completely to a random unique ID? this is a common situation, and I think it should be available.
We can use `uuid.uuid1()` function from python for this reason.
I can create a PR if you are interested.

**Comment by sehmaschine** [comment]
why not use the built-in signals instead?

**Comment by sharifzadesina** [comment]
@sehmaschine Cause we also have a help section in admin.
![screenshot from 2018-01-12 12-14-33](https://user-images.githubusercontent.com/15300551/34866589-4f521abc-f792-11e7-8c8e-1209aca4ba24.png)

**Comment by sehmaschine** [comment]
So all we need is to define a custom string for that section, right?

**Comment by sharifzadesina** [comment]
@sehmaschine I think we can implement this setting, cause it is common.

**Comment by sehmaschine** [comment]
I'm not fully convinced, because the settings are already quite complicated. However, with a PR (including tests) I'm happy to review – and if there are no backwards incompatible changes, I'll merge the PR.

**Comment by sharifzadesina** [comment]
@sehmaschine There won't be any BC break, I will send a PR.

**Comment by sehmaschine** [comment]
Great. Please take a look at the version namer – it would be nice to have something along that lines (in order to have a consistent API).

**Comment by sharifzadesina** [comment]
It won't change the behavior of the package, cause the setting will be false by default, I don't know what you mean by version number. I hope you don't mean we have to wait for a MINOR version to come up for this simple setting cause then I have to wait years :D, I think we can do it on a PATCH version, 3.9.2 will be OK.

**Comment by sehmaschine** [comment]
namer, not number ... see:
https://django-filebrowser.readthedocs.io/en/latest/settings.html#version-namer
