### ISSUE TITLE
django-filebrowser==3.5.3 and gif animation

### ISSUE THREAD

**Issue by IvanRyavkin** [sehmaschine/django-filebrowser#352]
Hello

```
{% version_object item.block.image 'index_list' as block_image %}

FILEBROWSER_VERSIONS
    'index_list': {
        'verbose_name': 'Index images',
        'width': 291, 'height': 199,
        'opts': 'upscale crop'

```

after that, the animation disappears

Is it possible to save gif animation?

**Comment by sehmaschine** [comment]
That's currently not supported. But it should be possible with Pillow – if you want to add a PR (including tests) we're happy to review.
