### ISSUE TITLE
can django-filebrowser  manage only the particular folder

### ISSUE THREAD

**Issue by d4wner** [sehmaschine/django-filebrowser#353]
Well，now I need to use django app to manage some particular folders.
But for some security reason, I could only give users the privilege of managing the particular folder.
For example,they could read the content of the file or do something others ,but could not upload some dangrous files.
I wonder if the plugin django-filebrowser could satisfy my needs.

Thx, looking forward to your reply~

**Comment by sehmaschine** [comment]
nope. we do not support user-specific folders. sorry.

**Comment by refael-kohen** [comment]
Hello,

It is possible to change the site.storage dynamically. 
I changed my code and now for each user specific path is opened.
I did it in django-filebrowser-no-grappelli version 3.7.2

I changed the function path_exists() in file:
PATH-TO-YOUR-PYTHON-ENV/lib/python2.7/site-packages/filebrowser/decorators.py, line:30

```
from filebrowser.sites import site
from django.core.files.storage import FileSystemStorage
from **YOUR-APPLICATION** import get_user_dir

def path_exists(site, function):
    "Check if the given path exists."
     def decorator(request, *args, **kwargs):
        user_name = request.user.username
        user_dir = get_user_dir(str(user_name))
 
        site.storage = FileSystemStorage(location=user_dir) 
        site.directory = "./"  
        .....
```
You need to implement the "get_user_dir" function, that gets user name (str) and return full path to folder **without the first '/'**. For example: 'home/username/'

It is works also when several users open the filebrowser at the same time.
