### ISSUE TITLE
ImproperlyConfigured at /admin/filebrowser/browse

### ISSUE THREAD

**Issue by jekoie** [sehmaschine/django-filebrowser#355]
i install django-filebrowswer and setting it by Quick start guide, but it throw the error?
what's wrong happed here, can anybody help me???

settings.py
```
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
FILEBROWSER_DIRECTORY = 'uploads/'


```

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/admin/filebrowser/browse/

Django Version: 2.0.6
Python Version: 3.6.5
Installed Applications:
['grappelli',
 'filebrowser',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py" in inner
  35.             response = get_response(request)

File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\filebrowser\decorators.py" in decorator
  37.             raise ImproperlyConfigured(_("Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?"))

Exception Type: ImproperlyConfigured at /admin/filebrowser/browse/
Exception Value: Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?

**Comment by sehmaschine** [comment]
You manually need to create the `FILEBROWSER_DIRECTORY` within `MEDIA_ROOT`.
