### ISSUE TITLE
example app

### ISSUE THREAD

**Issue by joinalahmed** [sehmaschine/django-filebrowser#357]
is there any example app to get started with this?
i was trying to use this for a personal project but, was unable t0 do so, can someone guide with me with a demo app?

**Comment by sehmaschine** [comment]
Please use the google-group for asking questions. IMO the docs are straightforward – if you have some experience with using Django (which is a requirement) it should be easy to get started. If you think the docs could be improved, please open a ticket with the details (or even a PR).
