### ISSUE TITLE
expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by MaxDragonheart** [sehmaschine/django-filebrowser#360]
Hi, I'm trying to install this package after having followed [this guide](https://django-filebrowser.readthedocs.io/en/stable/quickstart.html). I've created a simple app with this models.py

```
from django.db import models
from filebrowser.fields import FileBrowseField

class Post(models.Model):
    titolo = models.CharField(max_length=50)
    contenuti = models.TextField()
    image = FileBrowseField("Image", max_length=200, directory="images/", extensions=[".jpg"], blank=True)

    def __str__(self):
        return self.titolo
```

But when I try to add an image to a post Django show this error:

> TypeError at /admin/filebrowser/browse/
> expected str, bytes or os.PathLike object, not list

This is the complete error report:

> Environment:
> 
> 
> Request Method: GET
> Request URL: http://127.0.0.1:8000/admin/filebrowser/browse/?pop=1&dir=images/
> 
> Django Version: 2.0
> Python Version: 3.6.6
> Installed Applications:
> ['grappelli',
>  'filebrowser',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'testapp']
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> 
> 
> Traceback:
> 
> File "/var/www/html/dev/miosito/django/testsiteproject-django2.0/venv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
>   35.             response = get_response(request)
> 
> File "/var/www/html/dev/miosito/django/testsiteproject-django2.0/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   128.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/var/www/html/dev/miosito/django/testsiteproject-django2.0/venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
>   126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/var/www/html/dev/miosito/django/testsiteproject-django2.0/venv/lib/python3.6/site-packages/filebrowser/decorators.py" in decorator
>   35.         if get_path('', site=site) is None:
> 
> File "/var/www/html/dev/miosito/django/testsiteproject-django2.0/venv/lib/python3.6/site-packages/filebrowser/decorators.py" in get_path
>   18.         if site.storage.isdir(converted_path):
> 
> File "/var/www/html/dev/miosito/django/testsiteproject-django2.0/venv/lib/python3.6/site-packages/filebrowser/storage.py" in isdir
>   60.         return os.path.isdir(self.path(name))
> 
> File "/var/www/html/dev/miosito/django/testsiteproject-django2.0/venv/lib/python3.6/site-packages/django/core/files/storage.py" in path
>   321.         return safe_join(self.location, name)
> 
> File "/var/www/html/dev/miosito/django/testsiteproject-django2.0/venv/lib/python3.6/site-packages/django/utils/functional.py" in __get__
>   36.         res = instance.__dict__[self.name] = self.func(instance)
> 
> File "/var/www/html/dev/miosito/django/testsiteproject-django2.0/venv/lib/python3.6/site-packages/django/core/files/storage.py" in location
>   201.         return os.path.abspath(self.base_location)
> 
> File "/usr/lib/python3.6/posixpath.py" in abspath
>   371.     path = os.fspath(path)
> 
> Exception Type: TypeError at /admin/filebrowser/browse/
> Exception Value: expected str, bytes or os.PathLike object, not list

**I don't know what can I do.** 

Here pip3 list:

> Django (2.0)
> django-filebrowser (3.10.1)
> django-grappelli (2.11.1)
> Pillow (5.2.0)
> pip (9.0.1)
> pkg-resources (0.0.0)
> pytz (2018.5)
> setuptools (39.0.1)

**Comment by sehmaschine** [comment]
how did you add the image? using the admin interface?

**Comment by MaxDragonheart** [comment]
Yes the admin interface

**Comment by sehmaschine** [comment]
that's strange. I'm not able to reproduce this and we never had a similar feedback. can you please try to debug and add some details?

**Comment by MaxDragonheart** [comment]
Ok, how I can start a debug? I'm new in Django world...if you want I can share the project. It's a little test project that have a weight of 200kb.

**Comment by sehmaschine** [comment]
in that case it might be a good start to learn how to debug code (you'll need that sooner or later anyway).

**Comment by MaxDragonheart** [comment]
I'm learning, from a couple of day, test driven development. Any suggestions?

**Comment by sehmaschine** [comment]
hard to say in general. with the given issue, it should be straightforward by using print statements with the related functions (starting with the filebrowser). it's most probably an issue with your setup and how the path is constructed (could be related to the underlying storage engine which is defined with django) – it seems that the variable `path` is a list, but I have no idea why that should be the case.

**Comment by sehmaschine** [comment]
besides, you can also run the filebrowser tests, see:
https://django-filebrowser.readthedocs.io/en/stable/troubleshooting.html

**Comment by sehmaschine** [comment]
I'm closing this for now since no further details are given.
