### ISSUE TITLE
Versions in FileBrowseField

### ISSUE THREAD

**Issue by raagin** [sehmaschine/django-filebrowser#361]
I noticed, that sometimes users use versions in model FileBrowseField (from _versions folder). Sometimes they find somewhere link, sometimes they use FILEBROWSER_ADMIN_VERSIONS. 
This means that not original uploaded file go into database. I know, that in WYSIWYG-editors it is necessary. But usually files from FileObject have used template tag to generate version in template. And then you will have version from version. What do you think about it?

**Comment by sehmaschine** [comment]
Closing this since I'm not able to understand the issue and no further details have been given.
