### ISSUE TITLE
Dynamically set FileBrowserSite directory

### ISSUE THREAD

**Issue by stphnthiel** [sehmaschine/django-filebrowser#366]
Hi everyone,

first of all, thanks for providing such an excellent library. I really appreciate the hard work that went into it!

I would love to use the file browser for a site in which I want to isolate assets for each element in the database that has files into single folders (e.g. their pk, which is a uuid) so users who have access to an element only see files related to it.

I have seen some posts on how to hack it in, but all pretty old. Is there a way to do this reliably?

Here’s the two approaches I found (both do not seem to work in current versions of Django and DFB):

* Inheriting FileBrowserSite: https://stackoverflow.com/questions/21794867/dynamic-image-upload-browsing-path-for-django-tinymce
* Overwriting model save: https://stackoverflow.com/questions/7911172/django-filebrowser-model-specific-directory-parameter-for-filebrowserfield

Thanks!

**Comment by sehmaschine** [comment]
My idea would be to look at `FileBrowserSite.browse` since this function gets the request (and therefore the user). A filter might be applied here before `FileListing` is called.

Isolating the assets is not related to the filebrowser IMO.
