### ISSUE TITLE
Provide TinyMCE v4 support

### ISSUE THREAD

**Issue by XaviTorello** [sehmaschine/django-filebrowser#368]
Will be great to reach support for `TinyMCE v4`.

I.e, https://github.com/romanvm/django-tinymce4-lite or https://github.com/dani0805/django-tinymce4 integrates `TinyMCE v4` into our Django applications.

The non-grappeli version of `filebrowser` (https://github.com/smacker/django-filebrowser-no-grappelli) also supports it

**Comment by sehmaschine** [comment]
What exactly do you mean with "support"? Because a) TinyMCE is not part of the filebrowser (but grappelli instead) and b) you can easily use TinyMCE v4 right now. Or are there any specific issues you are relating to?

**Comment by sehmaschine** [comment]
Thanks! I'll reopen until this is merged with master.
