### ISSUE TITLE
Images with names ending in _big.jpg, _thumbnail.jpg, etc. do not show after upload

### ISSUE THREAD

**Issue by lucaswelper** [sehmaschine/django-filebrowser#37]
If a user uploads a file ending in "_big.jpg"  it will be treated as the big version of "house.jpg"  which doesn't exist.  I would recommend automatically adding a timestamp to the end of the filename if it matches one of the naming conventions you are using for the different versions.

**Comment by sehmaschine** [comment]
see https://github.com/sehmaschine/django-filebrowser/commit/9455f9bed5d7d5b8a8e99422fafef5356406a222

we do not filter the list anymore, if VERSIONS_BASEDIR is being used (which is recommended). so I guess this issue is solved.

please reopen if you think there's still an improvement to be made.
