### ISSUE TITLE
How can I change MEDIA_URL for filebrowser?

### ISSUE THREAD

**Issue by Nimond** [sehmaschine/django-filebrowser#372]
Hi, I need to change the uri where filebrowser takes imgs from. Now in project MEDIA_URL variable set as '/media/' and it is in use for different cases. Now preview in admin try to get https://.../media/img1.png (example), but I need https://.../uploads/img1.png (where are they realy located)

I try to set variable FILEBROWSER_MEDIA_URL in django settings, but it don't works.

**Comment by sehmaschine** [comment]
`MEDIA_URL` is defined with your django settings, see https://docs.djangoproject.com/en/2.2/ref/settings/#media-url
