### ISSUE TITLE
`MEDIA_URL` is defined with your django settings, see https://docs.djangoproject.com/en/2.2/ref/settings/#media-url

### ISSUE THREAD

**Issue by Nimond** [sehmaschine/django-filebrowser#373]
`MEDIA_URL` is defined with your django settings, see https://docs.djangoproject.com/en/2.2/ref/settings/#media-url

_Originally posted by @sehmaschine in https://github.com/sehmaschine/django-filebrowser/issues/372#issuecomment-510574881_

I need filebrowser use another value, because django's MEDIA_URL is used in another case and accessibility only for authorized users. I need filebrowser return in admin interface urls which can be used by no authorized users.

**Comment by sehmaschine** [comment]
In theory, you can view any directory with the FileBrowser. But I don't think you're able to use different MEDIA_URLs with Django. IMO this is more of an issue with Django thank it is with the FileBrowser.

That being said, I'm not even sure you really need to change `MEDIA_URL` if you just need a different location the FileBrowser points to (see `DIRECTORY` settings instead).
