### ISSUE TITLE
Version compatibility conflict with grapelli 2.13.1

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-filebrowser#374]
I tried to setup a new Virtual Environment on a production server using this line:
`pip install --upgrade "django" django-appconf django-extensions django-staticfiles feedparser idna mysqlclient Pillow pytz simplejson six unicodecsv daiquiri "django-filebrowser" "django-grappelli" urllib3 wheel selenium`

Which fails with this error message:
`django-filebrowser 3.11.1 has requirement django-grappelli<2.13,>=2.12, but you'll have django-grappelli 2.13.1 which is incompatible.`

Despite the serious-sounding error, it seems to have installed:

```
Package            Version    
------------------ -----------
daiquiri           1.5.0      
Django             2.2.3      
django-appconf     1.0.3      
django-extensions  2.2.1      
django-filebrowser 3.11.1     
django-grappelli   2.13.1     
django-staticfiles 1.2.1      
feedparser         5.2.1      
idna               2.8        
mysqlclient        1.4.2.post1
Pillow             6.1.0      
pip                19.2       
pytz               2019.1     
selenium           3.141.0    
setuptools         41.0.1     
simplejson         3.16.0     
six                1.12.0     
sqlparse           0.3.0      
unicodecsv         0.14.1     
urllib3            1.25.3     
wheel              0.33.4 
```

I'll have to test it out to see if it actually works....  I'll be back in a short while if it blows up.

**Comment by sehmaschine** [comment]
any updates on this? I don't see an issue here since filebrowser 3.11.1 supports django 1.2 and grappelli 2.12.

**Comment by sehmaschine** [comment]
@rcooke any ideas on how to solve the warning? IMO grappelli 2.12.x should be installed instead of 2.13.x here.

**Comment by sehmaschine** [comment]
there's now a new version compatible with django 2.2 and grappelli 2.13 as well as an update of the previous version. please re-open if this issue still exists.
