### ISSUE TITLE
All images are uploaded but are marked as "failed" when uploading using S3

### ISSUE THREAD

**Issue by emilpriver** [sehmaschine/django-filebrowser#376]
When im uploading image to s3 via filebrowser does the return message when uploading be "failed" but image is added to s3 and I am able to see the image when im browsing in filebrowser.

![ed761eb963dbd6df96858ceafbbd7ebb](https://user-images.githubusercontent.com/34039674/69378079-dde6fe00-0cad-11ea-9d08-519e1a76e18f.png)

**Comment by sehmaschine** [comment]
we do not support S3 (see #283), therefore I'm closing this issue. if someone comes up with a teste PR, I'm happy to review.
