### ISSUE TITLE
Default value should be iterable

### ISSUE THREAD

**Issue by raagin** [sehmaschine/django-filebrowser#378]
https://github.com/sehmaschine/django-filebrowser/blob/6e4c59e11844586a9dfbae9beeb684b3b7a93182/filebrowser/base.py#L257

**Comment by sehmaschine** [comment]
Please explain this issue more detailed.

**Comment by raagin** [comment]
If EXTESIONS will have no 'item', default value will set to None and this produce error in for... in cycle: TypeError: 'NoneType' object is not iterable

**Comment by sehmaschine** [comment]
Sorry, I don't get this. `item` referes to `SELECT_FORMATS` which needs to be available with `EXTENSIONS`.

**Comment by raagin** [comment]
Ok, thank you
