### ISSUE TITLE
Django 3.0

### ISSUE THREAD

**Issue by sehmaschine** [sehmaschine/django-filebrowser#380]

**Comment by UnMalNick** [comment]
is there any schedule to add support on Django 3.0?

**Comment by sehmaschine** [comment]
working on it ... but sorry, no schedule.

**Comment by sehmaschine** [comment]
stable/3.13.x has been out since 6th of january, but no feedback so far. I assume that all tests have been succesful and I'm therefore going to merge that branch with master.
