### ISSUE TITLE
Can't pickle <class 'boto3.resources.factory.s3.ServiceResource'>

### ISSUE THREAD

**Issue by dxmr** [sehmaschine/django-filebrowser#381]
I'm getting this error. Is this something related to **django-filebrowser**

Exception at /1!90O76admin/movies/movie/5656/
Can't pickle <class 'boto3.resources.factory.s3.ServiceResource'>: attribute lookup boto3.resources.factory.s3.ServiceResource failed

**Comment by sehmaschine** [comment]
I don't think it is, since FB does not support S3.
