### ISSUE TITLE
Refused to connect

### ISSUE THREAD

**Issue by OmidShojaee** [sehmaschine/django-filebrowser#396]
I can go to ```admin/filebrowser/browse```, upload files, and see and change uploaded files without any issue. Everything works fine.

I have ```django-tinymce``` too, and I see an ```upload``` button in the ```Insert/Edit Image``` window, but if I click on that a new window opens and I see ```127.0.0.1 refused to connect```.

I'm working in my development environment.

Please assist.

Environment:
Django 3.1.7
Django-TinyMCE 3.2.0
Django-FileBrowser 3.13.2
Django-Grappelli 2.14.3

**Comment by sehmaschine** [comment]
Can you please try without `django-tinyme`? We cannot comment on issues which are possibly related to another package.

**Comment by sehmaschine** [comment]
closing this since nor further details have been given.

**Comment by lugishr** [comment]
@OmidShojaee Did you solve the issue ? I have the same issue, `admin/filebrowser/browse` working fine but `upload` button in `django-tinymce` says `refused to connect`.

**Comment by OmidShojaee** [comment]
@lugishr No sorry. Nobody helped me here so I gave up and removed it.

**Comment by lugishr** [comment]
@OmidShojaee sorry to hear that, I had big hope that I would somehow make it work... Anyway, thank you for your quick reply.

**Comment by tatiblockchain** [comment]
I have the exact same problem with django-tinymce - still no solution?

**Comment by hikir1** [comment]
The `XFrameOptionsMiddleware` sets the `X-Frame-Options` http header to `DENY` by default. You can change this by setting `X_FRAME_OPTIONS = 'SAMEORIGIN'` in `settings.py`. This fixed the issue for me.
