### ISSUE TITLE
Frame loaded with http protocol 

### ISSUE THREAD

**Issue by rolycg** [sehmaschine/django-filebrowser#397]
Hi, 

I'm having an issue using filebrowser:

Mixed Content: The page at 'https://partial.gopeb.com/admin/blog/blog/add/' was loaded over HTTPS, but requested an insecure frame 'http://partial.gopeb.com/admin/filebrowser/browse/?pop=5&type=image'. This request has been blocked; the content must be served over HTTPS.

Any idea why is using http to load the frame? 

Thanks in advance,

Best,
Rolando

**Comment by sehmaschine** [comment]
that's a TinyMCE popup, right?

**Comment by rolycg** [comment]
Hi, yes.

**Comment by sehmaschine** [comment]
well ... at least you could check if there's a setting in order to use a secure connection. IMO it's either TinyMCE or the implementation of your filebrowser_callback (maybe you are using an absolute URL there).

**Comment by rolycg** [comment]
Well, I couldn't find a setting for this. I ended up importing TinyMCE module and editing views.py

`def filebrowser(request):
    try:
        fb_url = request.build_absolute_uri(reverse("fb_browse"))
    except Exception:
        fb_url = request.build_absolute_uri(reverse("filebrowser:fb_browse"))
        if not DEBUG:
            fb_url = fb_url.replace('http', 'https')

    return render(
        request,
        "tinymce/filebrowser.js",
        {"fb_url": fb_url},
        content_type="application/javascript",
    )`

In case someone else needs it. 

Thanks for the quick response and guide.
