### ISSUE TITLE
No clear settings

### ISSUE THREAD

**Issue by rikesh1212** [sehmaschine/django-filebrowser#398]
Please check the issue at 
https://stackoverflow.com/questions/67465226/how-to-solve-improperlyconfigured-at-admin-filebrowser-browse-error-finding-u

**Comment by sehmaschine** [comment]
yep – it says that the upload folder does not exist. not sure what exactly the issue is. please reopen with additional information (if you actually think it is a bug).

**Comment by rikesh1212** [comment]
settings.py
`MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
`FILEBROWSER_DIRECTORY=''  `

Same problem , improperly configured
