### ISSUE TITLE
Files with more than one extension (examples: .tar.gz, .tar.xz) are not permitted by _isAllowedExtension in filebrowser.js

### ISSUE THREAD

**Issue by afparsons** [sehmaschine/django-filebrowser#411]
If a programmer configures `django-filebrowser` in `settings.py` like so:

```python3
FILEBROWSER_EXTENSIONS = {
    ...,  # other entries elided
    'Archive': ['.zip', '.tar', '.tar.gz', '.tar.xz']
}
```

...then a user will be shown the error: `typeError: "{file} has invalid extension. Only {extensions} are allowed."` when trying to upload a compressed tarball.

This is because [`_isAllowedExtension()`](https://github.com/smacker/django-filebrowser-no-grappelli/blob/25b35ed5350ce90d324d9099be13d0b1121f62ec/filebrowser/static/filebrowser/js/fileuploader.js#L450) sees `myFile.tar.gz` as simply ending in `.gz`, which is not in `allowedExtensions`. 

```js
_isAllowedExtension: function(fileName){

    // this trims ".tar.gz" to ".gz"
    var ext = (-1 !== fileName.indexOf('.')) ? fileName.substr(fileName.lastIndexOf('.')).toLowerCase() : '';

    var allowed = this._options.allowedExtensions;

    if (!allowed.length){return true;}        
    
    for (var i=0; i<allowed.length; i++){
        if (allowed[i].toLowerCase() == ext){ return true;}    
    }
    
    return false;
}, 
```

The naive solution is to change `FILEBROWSER_EXTENSIONS` to accept `.xz` or `.gz` (or whatever relevant extension). However, I would argue that this is problematic, as simply accepting all files ending in `.gz` or `.xz` is not the same as only accepting `.tar.gz` or `.tar.xz`.

---

**Possible solution**

(please note I have almost no JavaScript experience and haven't tested this)

```js
_isAllowedExtension: function(fileName){

    var fileNameLower = fileName.toLowerCase()

    var allowed = this._options.allowedExtensions;
    if (!allowed.length){return true;}        
    
    for (var i=0; i<allowed.length; i++){
        if (fileNameLower.endsWith(allowed[i].toLowerCase())){ return true;}    
    }
    
    return false;
}, 
```

---

_Edit 1: formatting_

_Edit 2: add permalink to source code_

**Comment by sehmaschine** [comment]
Good point, thanks. We'll fix this with the next release.
