### ISSUE TITLE
doesnt work with pillow 10, please fix requirements.txt

### ISSUE THREAD

**Issue by Tauhid-Ahmed8009** [sehmaschine/django-filebrowser#416]
Please update requirements.txt to install Pillow==9.5.0 latest is 10 and it throws error: AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'.

**Comment by sehmaschine** [comment]
I'm in favour of changing `ANTIALIAS` instead ... see https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants
