### ISSUE TITLE
Moving files between folders

### ISSUE THREAD

**Issue by z-station** [sehmaschine/django-filebrowser#417]
I read the docs and code and didn't find UI actions/widgets for moving files between folders. Why is this functionality not supported? Should we expect it in the near future?

**Comment by sehmaschine** [comment]
it is not planned to implement something like this. the way we use files is that we usually store a reference to the file within the database – so moving the file also requires to update that path (so the db update is our trigger to actually move the file on the server). basically, we've never needed this.

**Comment by z-station** [comment]
Thanks for answer! Yes, I agree with your arguments! However, if I need to regroup hundreds of files, I need to delete them and upload them again
